### ISSUE TITLE
IdentityEncoder, iteration over 0-d tensor error

### ISSUE THREAD

**Issue by PetrochukM** [PetrochukM/PyTorch-NLP#55]
It's expected the IdentityEncoder can work with a scalar value:
```
>>> from torchnlp.text_encoders import IdentityEncoder
>>> i = IdentityEncoder([1])
>>> i.encode(1)
tensor([5])
>>> i.decode(i.encode(1))
1
>>> i.decode(i.encode(1)[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michaelp/.local/lib/python3.6/site-packages/torchnlp/text_encoders/identity_encoder.py", line 44, in decode
    tokens = [self.itos[index] for index in tensor]
  File "/Users/michaelp/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/tensor.py", line 381, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor
```

**Comment by PetrochukM** [comment]
Fixed: https://github.com/PetrochukM/PyTorch-NLP/pull/56
