### ISSUE TITLE
import error: fails to find sru.cu and no attribute 'encode' issue

### ISSUE THREAD

**Issue by jpilaul** [PetrochukM/PyTorch-NLP#64]
## Expected Behavior
`import torchnlp.nn as nn` should work

## Actual Behavior
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torchnlp/nn/__init__.py", line 8, in <module>
    from torchnlp.nn.sru import SRU
  File "/opt/conda/lib/python3.7/site-packages/torchnlp/nn/sru.py", line 68, in <module>
    SRU_CODE = open('sru.cu').read()
FileNotFoundError: [Errno 2] No such file or directory: 'sru.cu'
```
```
if I try within File /opt/conda/lib/python3.7/site-packages/torchnlp/nn, I get:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torchnlp/nn/__init__.py", line 8, in <module>
    from torchnlp.nn.sru import SRU
  File "/opt/conda/lib/python3.7/site-packages/torchnlp/nn/sru.py", line 69, in <module>
    SRU_PROG = Program(SRU_CODE.encode('utf-8'), 'sru_prog.cu'.encode('utf-8'))
  File "/opt/conda/lib/python3.7/site-packages/pynvrtc/compiler.py", line 52, in __init__
    include_names)
  File "/opt/conda/lib/python3.7/site-packages/pynvrtc/interface.py", line 200, in nvrtcCreateProgram
    c_char_p(encode_str(src)), c_char_p(encode_str(name)),
  File "/opt/conda/lib/python3.7/site-packages/pynvrtc/interface.py", line 54, in encode_str
    return s.encode("utf-8")
AttributeError: 'bytes' object has no attribute 'encode'
```
`sru.cu` is there but I get other errors down the line...

## Steps to Reproduce the Problem

1. python3.7
2. cuda 10
3. both pip installations yield the same errors
4. import torchnlp.nn as nn

**Comment by PetrochukM** [comment]
Hi!

Sorry for your issue. In the next version SRU will be removed, please use: https://github.com/taolei87/sru

Learn more: https://github.com/PetrochukM/PyTorch-NLP/pull/68

Thanks!
