### ISSUE TITLE
AttributeError: 'WeightDropGRU' object has no attribute '_flat_weights'

### ISSUE THREAD

**Issue by Kamin-At** [PetrochukM/PyTorch-NLP#87]
I normally called 
WeightDropGRU(input_size = num_input_features, hidden_size = hidden_size, \
                                 num_layers = num_layers, batch_first = True, dropout = dropout_gru, \
                                 bidirectional = bidirectional, weight_dropout=drop_weight)
on Mac everything works wekk but, on Linux, this error happened. (My Pytorch version is 1.13)

Traceback (most recent call last):
  File "exper_special.py", line 88, in <module>
    NER.to(device)
  File "/home/.pyenv/versions/anaconda3-2019.07/envs/allennlp_dw2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 426, in to
    return self._apply(convert)
  File "/home//.pyenv/versions/anaconda3-2019.07/envs/allennlp_dw2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/home/.pyenv/versions/anaconda3-2019.07/envs/allennlp_dw2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/home/.pyenv/versions/anaconda3-2019.07/envs/allennlp_dw2/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 124, in _apply
    self.flatten_parameters()
  File "/home/.pyenv/versions/anaconda3-2019.07/envs/allennlp_dw2/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 104, in flatten_parameters
    all_weights = self._flat_weights
  File "/home/.pyenv/versions/anaconda3-2019.07/envs/allennlp_dw2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'WeightDropGRU' object has no attribute '_flat_weights'

**Comment by simonrouse9461** [comment]
Same here! It looks like weight dropout doesn't work with cuda.

**Comment by PetrochukM** [comment]
This issue is the same as: https://github.com/PetrochukM/PyTorch-NLP/issues/77
